# Generated by Django 5.0.2 on 2024-02-21 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='coucou',
            field=models.IntegerField(default=0),
        ),
    ]
