# Generated by Django 5.0.2 on 2024-02-25 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_coucou'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='coucou',
        ),
    ]
