# Generated by Django 5.0.2 on 2024-02-23 17:54

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('bgg_number', models.IntegerField(blank=True, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Extension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('bgg_number', models.IntegerField(null=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extensions', to='games.game')),
            ],
        ),
        migrations.CreateModel(
            name='GameConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_players', models.IntegerField(default=1)),
                ('max_players', models.IntegerField(default=4)),
                ('score_min', models.IntegerField(default=0)),
                ('score_max', models.IntegerField()),
                ('extensions', models.ManyToManyField(blank=True, to='games.extension')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.game')),
            ],
        ),
        migrations.CreateModel(
            name='Play',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('game_configuration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plays', to='games.gameconfiguration')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('play', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.play')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('play', 'player')},
            },
        ),
        migrations.AddField(
            model_name='play',
            name='players',
            field=models.ManyToManyField(related_name='plays', through='games.PlayerScore', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='UserGameScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_score', models.IntegerField(default=0)),
                ('game_configuration', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_game_scores', to='games.gameconfiguration')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_scores', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'game_configuration')},
            },
        ),
    ]
