# Generated by Django 5.0.2 on 2024-02-25 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gameconfiguration',
            options={'ordering': ['game__name']},
        ),
    ]
