# Generated by Django 5.0.2 on 2024-02-20 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_alter_game_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extension',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
