# Generated by Django 5.0.2 on 2024-02-20 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_alter_extension_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extension',
            name='description',
        ),
        migrations.RemoveField(
            model_name='game',
            name='description',
        ),
    ]
