# Generated by Django 5.0.2 on 2024-02-21 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_remove_extension_description_remove_game_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='bgg_number',
            field=models.IntegerField(null=True),
        ),
    ]
