# Generated by Django 5.0.2 on 2024-02-21 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_game_bgg_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='extension',
            name='bgg_number',
            field=models.IntegerField(null=True),
        ),
    ]
