# Generated by Django 5.0.2 on 2024-02-21 19:29

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0006_extension_bgg_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Play',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('extensions', models.ManyToManyField(blank=True, to='games.extension')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.game')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('play', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.play')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('play', 'player')},
            },
        ),
        migrations.AddField(
            model_name='play',
            name='players',
            field=models.ManyToManyField(related_name='plays', through='games.PlayerScore', to=settings.AUTH_USER_MODEL),
        ),
    ]
