# Generated by Django 5.0.2 on 2024-02-21 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0008_usergamescore'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserGameScore',
        ),
    ]
