# Generated by Django 5.0.2 on 2024-02-22 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0010_usergamescore'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='score_max',
            field=models.IntegerField(default=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='score_min',
            field=models.IntegerField(default=0),
        ),
    ]
