# Generated by Django 5.0.2 on 2024-02-22 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0012_alter_game_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='bgg_number',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
